### ISSUE TITLE
Installation in Ubuntu

### ISSUE THREAD

**Issue by brycause** [OpenCMISS/setup#19]
There says that we shoul reach the directory `/OPENCMISS_ROOT/manage/build` but in the archive here in the project there is no carpet called `/build`

**Comment by sgenie68** [comment]
It looks like a typo, the correct path is OPENCMISS_ROOT/build/manage - I will take a look at the document

**Comment by brycause** [comment]
thank you for the answer. I'm actually right now trying to install it and there is no directory called build in the root carpet. The only carpet available is `/manage`

**Comment by sgenie68** [comment]
Hi, 
I already replied to you in the email but I didn't realise it wouldn't be added to the github replies - just for completeness I will copy my email to you here, so ignore it:

he best way to install OpenCMISS is the following sequence:

git clone https://github.com/OpenCMISS/setup.git
mkdir opencmiss
mkdir setup-build
cd setup-build

export CC=gcc
export CXX=g++
export FC=gfortran
cmake -DOPENCMISS_ROOT=../opencmiss -DOPENCMISS_LIBRARIES=iron ../setup
make

This way all the service directories are created during the setup phase and you can compile parts of the system easily later on

Cheers,
Gene

**Comment by brycause** [comment]
thank you very much Gene :^) 
I've tried again with this way, but again I get an error with it
let me get you a shot of it
![captura](https://user-images.githubusercontent.com/55007315/76491883-0412e400-63ec-11ea-964e-ac3c87d13f8b.png)

thanks for the help again

**Comment by sgenie68** [comment]
Can you send me the content of the OC_IRON_CONFIGURE_err.log, please?

**Comment by brycause** [comment]
Sure, here it goes
`CMake Error at extproj/stamp/OC_IRON-configure-Release.cmake:16 (message):
  Command failed: 1

   '/usr/bin/cmake' '--no-warn-unused-cli' '-DCMAKE_PREFIX_PATH=/home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake' '-DCMAKE_MODULE_PATH=/home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/share/cmake/Modules/OpenCMISS;/home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/share/cmake/Modules/FindModuleWrappers;/home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/share/cmake/Modules' '-DPACKAGE_CONFIG_DIR=cmake' '-DCMAKE_NO_SYSTEM_FROM_IMPORTED=YES' '-DCMAKE_DEBUG_POSTFIX=d' '-DCMAKE_POSITION_INDEPENDENT_CODE=YES' '-DOPENCMISS_INSTRUMENTATION=' '-DWARN_ALL=YES' '-DCHECK_ALL=YES' '-DCMAKE_INSTALL_DEFAULT_COMPONENT_NAME=Development' '-DCMAKE_INSTALL_PREFIX:PATH=/home/bryanaleman/OPENCMISS_ROOT/opencmiss/install' '-DCMAKE_BUILD_TYPE=Release' '-DBUILD_SHARED_LIBS=ON' '-DMPIEXEC_EXECUTABLE=/usr/bin/mpiexec' '-DMPI_VERSION=' '-DMPI_C_COMPILER=/usr/bin/mpicc' '-DCMAKE_C_COMPILER=/usr/bin/gcc' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG -Ofast' '-DCMAKE_C_FLAGS_DEBUG=-g -O0 -Wall' '-DMPI_CXX_COMPILER=/usr/bin/mpicxx' '-DCMAKE_CXX_COMPILER=/usr/bin/g++' '-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG -Ofast' '-DCMAKE_CXX_FLAGS_DEBUG=-g -O0 -Wall' '-DMPI_Fortran_COMPILER=/usr/bin/mpif77' '-DCMAKE_Fortran_COMPILER=/usr/bin/gfortran' '-DCMAKE_Fortran_FLAGS_RELEASE=-O3 -DNDEBUG -O3 -Ofast' '-DCMAKE_Fortran_FLAGS_DEBUG=-g -O0 -Wall -fbacktrace -Warray-temporaries -Wextra -Wsurprising -Wrealloc-lhs-all -finit-real=snan -fcheck=all' '-DBUILD_TESTS=ON' '-DWITH_CELLML=ON' '-DLIBXML2_FIND_SYSTEM=ON' '-DLIBXML2_VERSION=2.7.6' '-DCELLML_FIND_SYSTEM=OFF' '-DCELLML_VERSION=1.0' '-DLIBCELLML_FIND_SYSTEM=OFF' '-DLIBCELLML_VERSION=1.0' '-DWITH_FIELDML=ON' '-DFIELDML-API_FIND_SYSTEM=OFF' '-DFIELDML-API_VERSION=0.5.0' '-DWITH_HYPRE=ON' '-DHYPRE_FIND_SYSTEM=OFF' '-DHYPRE_VERSION=2.10.0' '-DWITH_SUNDIALS=ON' '-DSUNDIALS_FIND_SYSTEM=OFF' '-DSUNDIALS_VERSION=2.5' '-DWITH_MUMPS=ON' '-DMUMPS_FIND_SYSTEM=OFF' '-DMUMPS_VERSION=5.0.0' '-DWITH_SCALAPACK=ON' '-DSCALAPACK_FIND_SYSTEM=OFF' '-DSCALAPACK_VERSION=2.8' '-DBLAS_FIND_SYSTEM=TRUE' '-DBLAS_VERSION=3.5.0' '-DLAPACK_FIND_SYSTEM=ON' '-DLAPACK_VERSION=3.5.0' '-DWITH_PETSC=ON' '-DPETSC_FIND_SYSTEM=OFF' '-DPETSC_VERSION=3.6.1' '-DWITH_PROFILING=' '-DWITH_C_BINDINGS=ON' '-DWITH_Python_BINDINGS=ON' '-DFE_VIRTUALENV_INSTALL_PREFIX=/home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/virtual_environments' '-DFE_USE_VIRTUALENV=YES' '-GUnix Makefiles' '/home/bryanaleman/OPENCMISS_ROOT/opencmiss/src/iron'

  See also

    /home/bryanaleman/OPENCMISS_ROOT/opencmiss/build/iron/release/extproj/stamp/OC_IRON-configure-*.log


CMakeFiles/OC_IRON.dir/build.make:123: recipe for target '/home/bryanaleman/OPENCMISS_ROOT/opencmiss/build/iron/release/extproj/stamp/OC_IRON-configure' failed
make[8]: *** [/home/bryanaleman/OPENCMISS_ROOT/opencmiss/build/iron/release/extproj/stamp/OC_IRON-configure] Error 1
CMakeFiles/Makefile2:213: recipe for target 'CMakeFiles/OC_IRON.dir/all' failed
make[7]: *** [CMakeFiles/OC_IRON.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make[6]: *** [all] Error 2
CMakeFiles/manage_config.dir/build.make:68: recipe for target 'config/Release/stamp/manage_config-build' failed
make[5]: *** [config/Release/stamp/manage_config-build] Error 2
CMakeFiles/Makefile2:163: recipe for target 'CMakeFiles/manage_config.dir/all' failed
make[4]: *** [CMakeFiles/manage_config.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/setup_manage.dir/build.make:111: recipe for target 'setup_manage-prefix/src/setup_manage-stamp/setup_manage-build' failed
make[2]: *** [setup_manage-prefix/src/setup_manage-stamp/setup_manage-build] Error 2
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/setup_manage.dir/all' failed
make[1]: *** [CMakeFiles/setup_manage.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by sgenie68** [comment]
Sorry, I mean this file:

/home/bryanaleman/OPENCMISS_ROOT/opencmiss/build/iron/release/extproj/stamp/OC_IRON-configure-err.log

**Comment by brycause** [comment]
Yup, my mistake, let me copy that for you haha
`Traceback (most recent call last):
  File "/home/bryanaleman/OPENCMISS_ROOT/opencmiss/src/iron/utils/numpy_include.py", line 1, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
CMake Error at bindings/CMakeLists.txt:96 (message):
  Could not detect NumPy includes.  Unable to generate Python bindings for
  Iron.`


`

**Comment by sgenie68** [comment]
Yeap - it cannot find numpy module  - do you have it installed? What version of Python do you use?

**Comment by brycause** [comment]
I've got 2.7.17
Let me go ahead and install a 3 version

**Comment by brycause** [comment]
Thank you. I've already updated python and numpy package, but I've still got the same error

![captura_1](https://user-images.githubusercontent.com/55007315/76495646-869fa180-63f4-11ea-86ea-c53ef236f800.png)

Actually, all the times the problem is within the same directory

**Comment by sgenie68** [comment]
Can you check if you have virtualenv directory created in opencmiss/install directory?

**Comment by hsorby** [comment]
The contents of the file:
`/home/bryanaleman/OPENCMISS_ROOT/opencmiss/build/iron/release/extproj/stamp/OC_IRON-configure-err.log` 

and also the file:
`/home/bryanaleman/OPENCMISS_ROOT/opencmiss/build/iron/release/extproj/stamp/OC_IRON-configure-out.log`

would be really helpful in seeing what is going wrong.

**Comment by brycause** [comment]
@sgenie68 Thank you so much. I've already tried creating a new virtual enviroment in the install directory, but it didn't work either. @hsorby  Let me get here what I got in those files

OC_IRON-configure-out.log
`Not searching for unused variables given on the command line.
-- Iron::Instrumentation: 
-- Checking method: F77_HEADER
-- Checking method: F08_MODULE
-- Checking method: F90_MODULE
-- FindLLVM wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- FindZLIB wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- FindLibXml2 wrapper: System search enabled
-- FindLibXml2 wrapper: Trying to find version 2.7.6 on system in MODULE mode
-- FindLibXml2 wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- FindClang wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- FindCSim wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- Building with CELLML ()
-- Building with FIELDML (/home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake)
-- Looking for SCALAPACK..
-- FindLAPACK wrapper: System search enabled
-- FindLAPACK wrapper: Trying to find version 3.5.0 on system in MODULE mode
-- A library with BLAS API found.
-- FindLAPACK wrapper: Found: /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libblas.so;gfortran
-- FindBLAS wrapper: System search enabled
-- FindBLAS wrapper: Trying to find version  on system in MODULE mode
-- FindBLAS wrapper: Found: /usr/lib/x86_64-linux-gnu/libblas.so
-- FindSCALAPACK wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- Looking for SCALAPACK.. found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake
-- Looking for MUMPS..
-- FindPARMETIS wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- FindMUMPS wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- Looking for MUMPS.. found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake
-- Looking for HYPRE..
-- FindSUPERLU wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- FindHYPRE wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- Looking for HYPRE.. found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake
-- Looking for SUNDIALS..
-- FindSUNDIALS wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- Looking for SUNDIALS.. found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake
-- Looking for PETSC..
-- FindBZip2 wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- FindPASTIX wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- FindSUITESPARSE wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- FindSUPERLU_DIST wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- FindPETSC wrapper: Found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake in CONFIG mode
-- Looking for PETSC.. found at /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/cmake
-- Creating C bindings
-- Creating Python bindings
-- Configuring incomplete, errors occurred!
See also "/home/bryanaleman/OPENCMISS_ROOT/opencmiss/build/iron/release/CMakeFiles/CMakeOutput.log".
See also "/home/bryanaleman/OPENCMISS_ROOT/opencmiss/build/iron/release/CMakeFiles/CMakeError.log".`


OC_IRON-configure-err.log

`Traceback (most recent call last):
  File "/home/bryanaleman/OPENCMISS_ROOT/opencmiss/src/iron/utils/numpy_include.py", line 1, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
CMake Error at bindings/CMakeLists.txt:96 (message):
  Could not detect NumPy includes.  Unable to generate Python bindings for
  Iron.`


I don't know why it still says that I don't have pynumpy installed, I already prepared those when I installed all the requisites

**Comment by sgenie68** [comment]
Can you try, this, please? In opencmiss/install/virtual_environments there is another directory oclibs_venv_XXXX something - make sure it is created. Then do this:

source /home/bryanaleman/OPENCMISS_ROOT/opencmiss/install/virtual_environments/oclibs_venv_XXXX/bin/activate
pip install numpy
deactivate

and then try running make again

If pip command fails with "missing interpreter" error, try using this:

python -m pip install numpy

Cheers,
Gene

**Comment by sgenie68** [comment]
Hi, 

It just occurred to me that there might be a problem with the way virtual environment is being generated. Could you give me full path to the bin directory in the virtual_environment structure that OpenCMISS make generated?

Gene

**Comment by sgenie68** [comment]
I have made a small change in one of the cmake files to avoid the problem you are seeing - can you try updating your code and running the build again?
